<?xml version="1.0" encoding="utf-8"?><Database Name="MbkTest" Class="ClubMemberDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MBK;Initial Catalog=MbkTest;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MbkTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblMembers" Member="tblMembers">
    <Type Name="tblMember">
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>